In [1]:
import pandas as pd
import seaborn as sns

In [3]:
df = sns.load_dataset("iris")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df[['sepal_width','sepal_length','species']]

     sepal_width  sepal_length    species
0            3.5           5.1     setosa
1            3.0           4.9     setosa
2            3.2           4.7     setosa
3            3.1           4.6     setosa
4            3.6           5.0     setosa
5            3.9           5.4     setosa
6            3.4           4.6     setosa
7            3.4           5.0     setosa
8            2.9           4.4     setosa
9            3.1           4.9     setosa
10           3.7           5.4     setosa
11           3.4           4.8     setosa
12           3.0           4.8     setosa
13           3.0           4.3     setosa
14           4.0           5.8     setosa
15           4.4           5.7     setosa
16           3.9           5.4     setosa
17           3.5           5.1     setosa
18           3.8           5.7     setosa
19           3.8           5.1     setosa
20           3.4           5.4     setosa
21           3.7           5.1     setosa
22           3.6           4.6     setosa
23           3.3           5.1     setosa
24           3.4           4.8     setosa
25           3.0           5.0     setosa
26           3.4           5.0     setosa
27           3.5           5.2     setosa
28           3.4           5.2     setosa
29           3.2           4.7     setosa
..           ...           ...        ...
120          3.2           6.9  virginica
121          2.8           5.6  virginica
122          2.8           7.7  virginica
123          2.7           6.3  virginica
124          3.3           6.7  virginica
125          3.2           7.2  virginica
126          2.8           6.2  virginica
127          3.0           6.1  virginica
128          2.8           6.4  virginica
129          3.0           7.2  virginica
130          2.8           7.4  virginica
131          3.8           7.9  virginica
132          2.8           6.4  virginica
133          2.8           6.3  virginica
134          2.6           6.1  virginica
135          3.0           7.7  virginica
136          3.4           6.3  virginica
137          3.1           6.4  virginica
138          3.0           6.0  virginica
139          3.1           6.9  virginica
140          3.1           6.7  virginica
141          3.1           6.9  virginica
142          2.7           5.8  virginica
143          3.2           6.8  virginica
144          3.3           6.7  virginica
145          3.0           6.7  virginica
146          2.5           6.3  virginica
147          3.0           6.5  virginica
148          3.4           6.2  virginica
149          3.0           5.9  virginica

[150 rows x 3 columns]

In [6]:
df['sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
5      3.9
6      3.4
7      3.4
8      2.9
9      3.1
10     3.7
11     3.4
12     3.0
13     3.0
14     4.0
15     4.4
16     3.9
17     3.5
18     3.8
19     3.8
20     3.4
21     3.7
22     3.6
23     3.3
24     3.4
25     3.0
26     3.4
27     3.5
28     3.4
29     3.2
      ...
120    3.2
121    2.8
122    2.8
123    2.7
124    3.3
125    3.2
126    2.8
127    3.0
128    2.8
129    3.0
130    2.8
131    3.8
132    2.8
133    2.8
134    2.6
135    3.0
136    3.4
137    3.1
138    3.0
139    3.1
140    3.1
141    3.1
142    2.7
143    3.2
144    3.3
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [10]:
df.filter(regex='width')

     sepal_width  petal_width
0            3.5          0.2
1            3.0          0.2
2            3.2          0.2
3            3.1          0.2
4            3.6          0.2
5            3.9          0.4
6            3.4          0.3
7            3.4          0.2
8            2.9          0.2
9            3.1          0.1
10           3.7          0.2
11           3.4          0.2
12           3.0          0.1
13           3.0          0.1
14           4.0          0.2
15           4.4          0.4
16           3.9          0.4
17           3.5          0.3
18           3.8          0.3
19           3.8          0.3
20           3.4          0.2
21           3.7          0.4
22           3.6          0.2
23           3.3          0.5
24           3.4          0.2
25           3.0          0.2
26           3.4          0.4
27           3.5          0.2
28           3.4          0.2
29           3.2          0.2
..           ...          ...
120          3.2          2.3
121          2.8          2.0
122          2.8          2.0
123          2.7          1.8
124          3.3          2.1
125          3.2          1.8
126          2.8          1.8
127          3.0          1.8
128          2.8          2.1
129          3.0          1.6
130          2.8          1.9
131          3.8          2.0
132          2.8          2.2
133          2.8          1.5
134          2.6          1.4
135          3.0          2.3
136          3.4          2.4
137          3.1          1.8
138          3.0          1.8
139          3.1          2.1
140          3.1          2.4
141          3.1          2.3
142          2.7          1.9
143          3.2          2.3
144          3.3          2.5
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

[150 rows x 2 columns]

In [17]:
df.loc[2:5, ['sepal_length', 'petal_width']]

   sepal_length  petal_width
2           4.7          0.2
3           4.6          0.2
4           5.0          0.2
5           5.4          0.4

In [21]:
df.iloc[2:5, [1, 2, 4]]

   sepal_width  petal_length species
2          3.2           1.3  setosa
3          3.1           1.5  setosa
4          3.6           1.4  setosa